# permissions for end users to view certs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-viewer-role
rules:
- apiGroups:
  - test.redhat.com
  resources:
  - certs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.redhat.com
  resources:
  - certs/status
  verbs:
  - get
